### ISSUE TITLE
Jvm Crashes occassionaly with Lucene 8.10.0, JDK 11.0.15+10

### ISSUE THREAD

**Issue by sosohu** [apache/lucene#12863] opened 2023-12-01 02:34 UTC
### Description

I used the Lucene 8.10.0 inside my project, and we found a JVM crash with the jstack as below:

```
"main" #1 prio=5 tid=0x00007f780c042000 nid=0x3503 runnable [0x0000000000000000]
  java.lang.Thread.State: RUNNABLE
  JavaThread state: _thread_in_java
- java.nio.ByteBuffer.get(byte[], int, int) @bci=49, line=745 (Compiled frame; information may be imprecise)
- java.nio.DirectByteBuffer.get(byte[], int, int) @bci=145, line=318 (Compiled frame)
- org.apache.lucene.store.ByteBufferGuard.getBytes(java.nio.ByteBuffer, byte[], int, int) @bci=9, line=94 (Compiled frame)
- org.apache.lucene.store.ByteBufferIndexInput.readBytes(byte[], int, int) @bci=11, line=99 (Compiled frame)
- org.apache.lucene.codecs.blocktree.CompressionAlgorithm$1.read(org.apache.lucene.store.DataInput, byte[], int) @bci=4, line=33 (Compiled frame)
- org.apache.lucene.codecs.blocktree.SegmentTermsEnumFrame.loadBlock() @bci=313, line=194 (Compiled frame)
- org.apache.lucene.codecs.blocktree.SegmentTermsEnum.seekExact(org.apache.lucene.util.BytesRef) @bci=804, line=509 (Compiled frame)
- org.apache.lucene.index.TermStates.loadTermsEnum(org.apache.lucene.index.LeafReaderContext, org.apache.lucene.index.Term) @bci=26, line=124 (Compiled frame)
- org.apache.lucene.index.TermStates.get(org.apache.lucene.index.LeafReaderContext) @bci=67, line=187 (Compiled frame)
- org.apache.lucene.search.TermQuery$TermWeight.getTermsEnum(org.apache.lucene.index.LeafReaderContext) @bci=76, line=134 (Compiled frame)
- org.apache.lucene.search.TermQuery$TermWeight.scorer(org.apache.lucene.index.LeafReaderContext) @bci=59, line=109 (Compiled frame)
- org.apache.lucene.search.Weight.scorerSupplier(org.apache.lucene.index.LeafReaderContext) @bci=2, line=148 (Compiled frame)
- org.apache.lucene.search.LRUQueryCache$CachingWrapperWeight.scorerSupplier(org.apache.lucene.index.LeafReaderContext) @bci=58, line=727 (Compiled frame)
- org.apache.lucene.search.BooleanWeight.scorerSupplier(org.apache.lucene.index.LeafReaderContext) @bci=115, line=379 (Compiled frame)
- org.apache.lucene.search.LRUQueryCache$CachingWrapperWeight.scorerSupplier(org.apache.lucene.index.LeafReaderContext) @bci=58, line=727 (Compiled frame)
- org.apache.lucene.search.BooleanWeight.scorerSupplier(org.apache.lucene.index.LeafReaderContext) @bci=115, line=379 (Compiled frame)
- org.apache.lucene.search.LRUQueryCache$CachingWrapperWeight.scorerSupplier(org.apache.lucene.index.LeafReaderContext) @bci=58, line=727 (Compiled frame)
- org.apache.lucene.search.BooleanWeight.scorerSupplier(org.apache.lucene.index.LeafReaderContext) @bci=115, line=379 (Compiled frame)
- org.apache.lucene.search.BooleanWeight.scorer(org.apache.lucene.index.LeafReaderContext) @bci=2, line=344 (Compiled frame)
- org.apache.lucene.search.Weight.bulkScorer(org.apache.lucene.index.LeafReaderContext) @bci=2, line=182 (Compiled frame)
- org.apache.lucene.search.BooleanWeight.bulkScorer(org.apache.lucene.index.LeafReaderContext) @bci=30, line=338 (Compiled frame)
- org.apache.lucene.search.LRUQueryCache$CachingWrapperWeight.bulkScorer(org.apache.lucene.index.LeafReaderContext) @bci=58, line=838 (Compiled frame)
- org.apache.lucene.search.IndexSearcher.search(java.util.List, org.apache.lucene.search.Weight, org.apache.lucene.search.Collector) @bci=51, line=656 (Interpreted frame)
- org.apache.lucene.search.IndexSearcher.search(org.apache.lucene.search.Query, org.apache.lucene.search.Collector) @bci=24, line=443 (Interpreted frame)
```

Here is my JDK info:
```
java.runtime.version = 11.0.15+10
java.vm.vendor = Eclipse Adoptium
java.vm.name = OpenJDK 64-Bit Server VM
java.vendor.version = Temurin-11.0.15+10
```

VM Flags:
```
Non-default VM flags: -XX:CICompilerCount=18 -XX:ConcGCThreads=11 -XX:G1ConcRefinementThreads=43 -XX:G1HeapRegionSize=1048576 -XX:GCDrainStackTargetSize=64 -XX:InitialHeapSize=1258291200 -XX:MarkStackSize=4194304 -XX:MaxHeapSize=1258291200 -XX:MaxNewSize=754974720 -XX:MinHeapDeltaBytes=1048576 -XX:NonNMethodCodeHeapSize=8769992 -XX:NonProfiledCodeHeapSize=121444124 -XX:ProfiledCodeHeapSize=121444124 -XX:ReservedCodeCacheSize=251658240 -XX:+SegmentedCodeCache -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseFastUnorderedTimeStamps -XX:+UseG1GC
Command line:  -Drefine.verbosity=error -Dlog4j2.formatMsgNoLookups=true -Xmx1200M vfprintf -Dlog4j2.formatMsgNoLookups=true
```

Could someone help to confirm if this issue is caused by Lucene or a JVM issue? 
Manay thanks

### Version and environment details
Lucene 8.10.0
OpenJDK 11.0.15+10

**Comment by msokolov** [comment] 2023-12-01 14:52
If the JVM crashes, it's generally considered a JVM bug. I'll note there is a more recent JDK 11 release - they seem to be up to 11.0.20. Have you considered upgrading? These point release generally include bug fixes, although I can't speak to whether this particular issue has been addressed.

**Comment by rmuir** [comment] 2023-12-01 15:27
I don't think its a jvm bug. This is what happens when you try to read from a closed indexreader that is backed by mmap. because we've unmapped the byte buffer  when `close()` was called -> SIGSEGV.

So it is a bug in the application (accessing close'd indexreader), but it causes the JVM crash. It is a tale as old as time, you can find numerous threads on it elsewhere. I'm not gonna repeat it all again.

We make a best effort to detect such abuses and prevent this, but its not possible to do safely without using @uschindler 's Panama-based provider and a modern JVM.

So either:
* fix your code not to access close'd indexreaders
* upgrade to recent lucene and java and use panama provider. You will get AlreadyClosedException or similar instead.
* call `setUseUnmap(false)` on your MMapDirectory. The downside is much disk and address space will now be tied to the java garbage collector...

**Closed by rmuir** 2023-12-01 15:27 UTC
Labels: type:bug

**Comment by uschindler** [comment] 2023-12-01 15:41
Thanks @rmuir,
I can confirm the above pattern happens when you access an IndexReader/IndexSearcher form another thread if it was closed.

To see AlreadyClosedExceptions you need to upgrade to at least Lucene ~9.5 (better use latest 9.9) and use Java 19 or later. This configuration will give you a AlreadyClosedException instead of crashing your JVM.

**Comment by msokolov** [comment] 2023-12-03 00:08
Thanks for explaining, @rmuir, @uschindler

**Comment by sosohu** [comment] 2023-12-05 02:25
Thank you very much  @rmuir, @uschindler.  Yes, there are many threads running at the same time and we have a managed reference count to close the reader, maybe there are some issues when increae or decrease the reference count. I will try to investigate the root cause in application.
Besides, @uschindler could you please provide the related pull request for this issue?  We did not plan to upgrade Lucene recently, I wonder to know if we can resolve this issue by cherry pick the fix and upgrading Java according? Many thanks!

**Comment by uschindler** [comment] 2023-12-06 08:51
> Thank you very much @rmuir, @uschindler. Yes, there are many threads running at the same time and we have a managed reference count to close the reader, maybe there are some issues when increase or decrease the reference count. I will try to investigate the root cause in application. Besides, @uschindler could you please provide the related pull request for this issue? We did not plan to upgrade Lucene recently, I wonder to know if we can resolve this issue by cherry pick the fix and upgrading Java according? Many thanks!

You can't backport this as this is a completely different implementation which does not have the problem.

Generally you should fix your code because the other implementation wouldn't solve the original issue, the queries would still fail, but throw AlreadyClosedException. If that's better?

If you are interested, see here: https://pretalx.com/bbuzz22/talk/WYC9ZB/

There's no single pull request and it has different implementations for each java version. It also requires MRJAR files.

To help you finding your bug, use the suggestions provided by Robert: change directory implementation to NIOFSDirectory and test (be aware that it will be a lot slower depending on usage) and then watch for AlreadyClosedException and find the root cause.
